<?php

$clientes = [
    ['id' => 1, 'nombre' => 'Juan', 'apellidos' => 'Pérez Gómez', 'telefonos' => '123456789', 'email' => 'juan.perez1@example.com'],
    ['id' => 2, 'nombre' => 'María', 'apellidos' => 'García López', 'telefonos' => '987654321', 'email' => 'maria.garcia2@example.com'],
    ['id' => 3, 'nombre' => 'Carlos', 'apellidos' => 'Sánchez Rodríguez', 'telefonos' => '555123456', 'email' => 'carlos.sanchez3@example.com'],
    ['id' => 4, 'nombre' => 'Ana', 'apellidos' => 'Martínez Fernández', 'telefonos' => '333987654', 'email' => 'ana.martinez4@example.com'],
    ['id' => 5, 'nombre' => 'Luis', 'apellidos' => 'Hernández Ruiz', 'telefonos' => '777123456', 'email' => 'luis.hernandez5@example.com'],
    ['id' => 6, 'nombre' => 'Sofía', 'apellidos' => 'Torres Sánchez', 'telefonos' => '888456789', 'email' => 'sofia.torres6@example.com'],
    ['id' => 7, 'nombre' => 'Miguel', 'apellidos' => 'Ramírez López', 'telefonos' => '999789456', 'email' => 'miguel.ramirez7@example.com'],
    ['id' => 8, 'nombre' => 'Lucía', 'apellidos' => 'Morales Castillo', 'telefonos' => '666123789', 'email' => 'lucia.morales8@example.com'],
    ['id' => 9, 'nombre' => 'Jorge', 'apellidos' => 'Díaz Pérez', 'telefonos' => '444654789', 'email' => 'jorge.diaz9@example.com'],
    ['id' => 10, 'nombre' => 'Marta', 'apellidos' => 'Ortiz García', 'telefonos' => '222987654', 'email' => 'marta.ortiz10@example.com'],
    ['id' => 11, 'nombre' => 'Daniel', 'apellidos' => 'Fernández Gómez', 'telefonos' => '333456789', 'email' => 'daniel.fernandez11@example.com'],
    ['id' => 12, 'nombre' => 'Sara', 'apellidos' => 'Rojas López', 'telefonos' => '111654987', 'email' => 'sara.rojas12@example.com'],
    ['id' => 13, 'nombre' => 'Alberto', 'apellidos' => 'Cruz Martínez', 'telefonos' => '555321987', 'email' => 'alberto.cruz13@example.com'],
    ['id' => 14, 'nombre' => 'Claudia', 'apellidos' => 'Soto Torres', 'telefonos' => '888123456', 'email' => 'claudia.soto14@example.com'],
    ['id' => 15, 'nombre' => 'Raúl', 'apellidos' => 'Navarro Ramos', 'telefonos' => '999456123', 'email' => 'raul.navarro15@example.com'],
    ['id' => 16, 'nombre' => 'Valeria', 'apellidos' => 'Romero Díaz', 'telefonos' => '666789123', 'email' => 'valeria.romero16@example.com'],
    ['id' => 17, 'nombre' => 'Andrés', 'apellidos' => 'Pacheco Cruz', 'telefonos' => '444987654', 'email' => 'andres.pacheco17@example.com'],
    ['id' => 18, 'nombre' => 'Elena', 'apellidos' => 'Fuentes Sánchez', 'telefonos' => '222654789', 'email' => 'elena.fuentes18@example.com'],
    ['id' => 19, 'nombre' => 'Victor', 'apellidos' => 'Ibáñez Torres', 'telefonos' => '111987456', 'email' => 'victor.ibanez19@example.com'],
    ['id' => 20, 'nombre' => 'Paula', 'apellidos' => 'Castro Gómez', 'telefonos' => '555123654', 'email' => 'paula.castro20@example.com'],
    ['id' => 21, 'nombre' => 'Fernando', 'apellidos' => 'López Hernández', 'telefonos' => '888456123', 'email' => 'fernando.lopez21@example.com'],
    ['id' => 22, 'nombre' => 'Isabel', 'apellidos' => 'Medina Ruiz', 'telefonos' => '999789654', 'email' => 'isabel.medina22@example.com'],
    ['id' => 23, 'nombre' => 'Héctor', 'apellidos' => 'Blanco Pérez', 'telefonos' => '666321987', 'email' => 'hector.blanco23@example.com'],
    ['id' => 24, 'nombre' => 'Adriana', 'apellidos' => 'Campos Ortiz', 'telefonos' => '444456123', 'email' => 'adriana.campos24@example.com'],
    ['id' => 25, 'nombre' => 'Emilio', 'apellidos' => 'Guzmán López', 'telefonos' => '222654123', 'email' => 'emilio.guzman25@example.com'],
    ['id' => 26, 'nombre' => 'Camila', 'apellidos' => 'Suárez Torres', 'telefonos' => '111789654', 'email' => 'camila.suarez26@example.com'],
    ['id' => 27, 'nombre' => 'Antonio', 'apellidos' => 'Vargas Martínez', 'telefonos' => '555987321', 'email' => 'antonio.vargas27@example.com'],
    ['id' => 28, 'nombre' => 'Patricia', 'apellidos' => 'Reyes Ramos', 'telefonos' => '888123987', 'email' => 'patricia.reyes28@example.com'],
    ['id' => 29, 'nombre' => 'Sebastián', 'apellidos' => 'Quintero Díaz', 'telefonos' => '999654321', 'email' => 'sebastian.quintero29@example.com'],
    ['id' => 30, 'nombre' => 'Laura', 'apellidos' => 'Lara Fuentes', 'telefonos' => '666987123', 'email' => 'laura.lara30@example.com']
];
?>